name: Symfony CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: symfony
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
        coverage: pcov
        tools: composer:v2

    - name: Set DATABASE_URL environment variable
      run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Check Symfony requirements
      run: php bin/console about

    - name: Créer la base de données de test
      run: php bin/console doctrine:database:create --env=test

    - name: Créer le schéma de la base de données
      run: php bin/console doctrine:schema:create --env=test

    - name: Charger les fixtures
      run: php bin/console doctrine:fixtures:load --no-interaction --env=test

    - name: Print DATABASE_URL
      run: echo $DATABASE_URL

    - name: Run PHPUnit tests
      run: ./vendor/bin/phpunit --coverage-text
      env:
        KERNEL_CLASS: 'App\Kernel'
